'''
In this part of the assignment, you will create a small graphical Python program. The program will read
two integers as input from the user. Its output will be a “smiley” (loosely defined) centered on the
position specified by the user. For example, if the user enters 400 and 300 as input, then the face
should be centered in the window. If the user enters 0 and 0, then the face should be centered in the
upper left corner of the window, with part of it cut off by the edge of the window. Use the
SimpleGraphics library that you were introduced to previously to complete this task.

• The image generated by your program should be some sort of a face that uses most of the
drawing area.
• The image generated by your program must use at least 4 distinct colors.
• The image generated by your program must use at least 4 different graphics primitives such as
ellipses, polygons, rectangles, text, etc.
• Your program may not load images or use other features that require files beyond your .py file.
Please use standard fonts such as Arial or Times if you choose to include text in your image.
• Do not resize the window.
• Your program should read only two input values: the x-position and the y-position of the center
of the face.
• Your program must include appropriate comments, including a comment at the top of your file
that includes your name and student number and describes the purpose of your program.
There should also be comments within the program that indicate which lines of code draw
different parts of the face (eyes, nose, hair, ears, mouth, etc.).
• You do not need to replace numbers used to control the positions of shapes with named
constants.
• Do not display your student number as part of the image.
'''

from SimpleGraphics import *
# Is there no way to make the window wait to open until something is drawn?

def main():
    print('This program takes coordinates as input and display a smiley face at that location.\n'
    'Note: The default window size is 800 x 600.')

    x_coord = get_coord("x")
    y_coord = get_coord("y")

    ellipse(x_coord-50, y_coord-50, 100, 100)

def get_coord(type):
    getting_coord = True
    while getting_coord:
        coord = input(f"Please enter the {type} coordinate: ")

        try:
            int(coord) # does not actually convert coord to int but tests if it can do so successfully
        except ValueError:
            print("Error: The value entered must be a number.")
            continue # ends the current loop

        if 0 <= int(coord) <= (800 if type == "x" else 600):
            return int(coord)
        else:
            print(f"Error: The {type} value must be between 0 and {800 if type == "x" else 600}.")

if __name__=="__main__":
    main()